### ISSUE TITLE
Реализация PVar'ов и SVar'ов

### ISSUE THREAD

**Issue by NexiusTailer** [Daniel-Cortez/pawn-misc#1]
Недавно при поиске реализации одной из имеющихся здесь функций заметил этот репозиторий. Как я понял, цель была собрать различные функции, которые не относятся напрямую к работе с данными игроков/синхронизацией/сампу в целом (ну, по крайней мере пока вижу именно такие из представленных). Поскольку это всё ещё может быть полезно людям, разрабатывающим мультиплееры вроде закрытого RW:MP (сейчас как минимум в активной разработке есть OpenMP и [VMP](https://vk.com/vicemultiplayer)), я думаю свободные реализации наиболее общих функций, которые были добавлены в сампе уже его разработчиком, будут также полезны каким-то из этих людей в перспективе. В первую очередь система PVar'ов и SVar'ов была бы здесь очень кстати.

**Comment by Daniel-Cortez** [comment]
> Как я понял, цель была собрать различные функции, которые не относятся напрямую к работе с данными игроков/синхронизацией/сампу в целом (ну, по крайней мере пока вижу именно такие из представленных).

Изначально да, реализации `VectorSize()` и `SHA256_PassHash()` предназначались для RWMP, но в дальнейшем разработчики мультиплеера (не буду показывать пальцем на конкретных людей) решили, что сами могут сделать лучше, добавив к `SHA256_PassHash()` поддержку устаревших алгоитмов MD5 и SHA1, и непонятно зачем реализовав `VectorSize()` с использованием векторных инструкций (заодно ещё и повысив требования сервера к железу ради одной-единственной функции).
Как бы то ни было, в дальнейшем репозиторий может быть использован для размещения в нём инклудов/фильтрскриптов. Пока что у меня нет по нему чётких планов.

> я думаю свободные реализации наиболее общих функций, которые были добавлены в сампе уже его разработчиком, будут также полезны каким-то из этих людей в перспективе. В первую очередь система PVar'ов и SVar'ов была бы здесь очень кстати.

Если кому-то они действительно нужны - пусть напишут. Иначе это с 99% вероятностью будет впустую потраченное время и усилия, как в случае с RWMP.
